run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gocritic

linters-settings:
  goimports:
    local-prefixes: github.com/kinetria/kinetria-back

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
