// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const appendAuditLog = `-- name: AppendAuditLog :exec
INSERT INTO audit_log (id, user_id, entity_type, entity_id, action, action_data, occurred_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AppendAuditLogParams struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.UUID             `json:"entity_id"`
	Action     string                `json:"action"`
	ActionData pqtype.NullRawMessage `json:"action_data"`
	OccurredAt time.Time             `json:"occurred_at"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
}

func (q *Queries) AppendAuditLog(ctx context.Context, arg AppendAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, appendAuditLog,
		arg.ID,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActionData,
		arg.OccurredAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
