// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercises.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const existsExerciseByIDAndWorkoutID = `-- name: ExistsExerciseByIDAndWorkoutID :one
SELECT EXISTS(
    SELECT 1 FROM exercises WHERE id = $1 AND workout_id = $2
) AS exists
`

type ExistsExerciseByIDAndWorkoutIDParams struct {
	ID        uuid.UUID `json:"id"`
	WorkoutID uuid.UUID `json:"workout_id"`
}

func (q *Queries) ExistsExerciseByIDAndWorkoutID(ctx context.Context, arg ExistsExerciseByIDAndWorkoutIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsExerciseByIDAndWorkoutID, arg.ID, arg.WorkoutID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
