// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: exercises.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const existsExerciseByIDAndWorkoutID = `-- name: ExistsExerciseByIDAndWorkoutID :one
SELECT EXISTS(
    SELECT 1 FROM workout_exercises WHERE exercise_id = $1 AND workout_id = $2
) AS exists
`

type ExistsExerciseByIDAndWorkoutIDParams struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	WorkoutID  uuid.UUID `json:"workout_id"`
}

func (q *Queries) ExistsExerciseByIDAndWorkoutID(ctx context.Context, arg ExistsExerciseByIDAndWorkoutIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsExerciseByIDAndWorkoutID, arg.ExerciseID, arg.WorkoutID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findWorkoutExerciseID = `-- name: FindWorkoutExerciseID :one
SELECT id FROM workout_exercises WHERE exercise_id = $1 AND workout_id = $2
`

type FindWorkoutExerciseIDParams struct {
	ExerciseID uuid.UUID `json:"exercise_id"`
	WorkoutID  uuid.UUID `json:"workout_id"`
}

func (q *Queries) FindWorkoutExerciseID(ctx context.Context, arg FindWorkoutExerciseIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, findWorkoutExerciseID, arg.ExerciseID, arg.WorkoutID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listExercisesByWorkoutID = `-- name: ListExercisesByWorkoutID :many
SELECT 
    e.id, 
    e.name, 
    e.thumbnail_url, 
    e.muscles,
    we.sets, 
    we.reps, 
    we.rest_time, 
    we.weight, 
    we.order_index
FROM exercises e
INNER JOIN workout_exercises we ON e.id = we.exercise_id
WHERE we.workout_id = $1
ORDER BY we.order_index ASC
`

type ListExercisesByWorkoutIDRow struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	ThumbnailUrl string          `json:"thumbnail_url"`
	Muscles      json.RawMessage `json:"muscles"`
	Sets         int32           `json:"sets"`
	Reps         string          `json:"reps"`
	RestTime     int32           `json:"rest_time"`
	Weight       int32           `json:"weight"`
	OrderIndex   int32           `json:"order_index"`
}

func (q *Queries) ListExercisesByWorkoutID(ctx context.Context, workoutID uuid.UUID) ([]ListExercisesByWorkoutIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listExercisesByWorkoutID, workoutID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExercisesByWorkoutIDRow
	for rows.Next() {
		var i ListExercisesByWorkoutIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ThumbnailUrl,
			&i.Muscles,
			&i.Sets,
			&i.Reps,
			&i.RestTime,
			&i.Weight,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
