// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	EntityType string                `json:"entity_type"`
	EntityID   uuid.UUID             `json:"entity_id"`
	Action     string                `json:"action"`
	ActionData pqtype.NullRawMessage `json:"action_data"`
	OccurredAt time.Time             `json:"occurred_at"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
}

type Exercise struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	ThumbnailUrl string          `json:"thumbnail_url"`
	Muscles      json.RawMessage `json:"muscles"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	WorkoutID  uuid.UUID    `json:"workout_id"`
	Status     string       `json:"status"`
	Notes      string       `json:"notes"`
	StartedAt  time.Time    `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type SetRecord struct {
	ID                uuid.UUID     `json:"id"`
	SessionID         uuid.UUID     `json:"session_id"`
	SetNumber         int32         `json:"set_number"`
	Weight            int32         `json:"weight"`
	Reps              int32         `json:"reps"`
	Status            string        `json:"status"`
	RecordedAt        time.Time     `json:"recorded_at"`
	WorkoutExerciseID uuid.NullUUID `json:"workout_exercise_id"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	Email           string         `json:"email"`
	Name            string         `json:"name"`
	PasswordHash    string         `json:"password_hash"`
	ProfileImageUrl sql.NullString `json:"profile_image_url"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Workout struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        string    `json:"type"`
	Intensity   string    `json:"intensity"`
	Duration    int32     `json:"duration"`
	ImageUrl    string    `json:"image_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type WorkoutExercise struct {
	ID         uuid.UUID `json:"id"`
	WorkoutID  uuid.UUID `json:"workout_id"`
	ExerciseID uuid.UUID `json:"exercise_id"`
	Sets       int32     `json:"sets"`
	Reps       string    `json:"reps"`
	RestTime   int32     `json:"rest_time"`
	Weight     int32     `json:"weight"`
	OrderIndex int32     `json:"order_index"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
