// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package queries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, workout_id, started_at, status, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	WorkoutID uuid.UUID `json:"workout_id"`
	StartedAt time.Time `json:"started_at"`
	Status    string    `json:"status"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.WorkoutID,
		arg.StartedAt,
		arg.Status,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const findActiveSessionByUserID = `-- name: FindActiveSessionByUserID :one
SELECT id, user_id, workout_id, started_at, finished_at, status, notes, created_at, updated_at
FROM sessions
WHERE user_id = $1 AND status = 'active'
LIMIT 1
`

type FindActiveSessionByUserIDRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	WorkoutID  uuid.UUID    `json:"workout_id"`
	StartedAt  time.Time    `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
	Status     string       `json:"status"`
	Notes      string       `json:"notes"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

func (q *Queries) FindActiveSessionByUserID(ctx context.Context, userID uuid.UUID) (FindActiveSessionByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, findActiveSessionByUserID, userID)
	var i FindActiveSessionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSessionByID = `-- name: FindSessionByID :one
SELECT id, user_id, workout_id, started_at, finished_at, status, notes, created_at, updated_at
FROM sessions
WHERE id = $1
`

type FindSessionByIDRow struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	WorkoutID  uuid.UUID    `json:"workout_id"`
	StartedAt  time.Time    `json:"started_at"`
	FinishedAt sql.NullTime `json:"finished_at"`
	Status     string       `json:"status"`
	Notes      string       `json:"notes"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

func (q *Queries) FindSessionByID(ctx context.Context, id uuid.UUID) (FindSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findSessionByID, id)
	var i FindSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WorkoutID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompletedSessionsByDateRange = `-- name: GetCompletedSessionsByDateRange :many
SELECT 
    id, 
    user_id, 
    workout_id, 
    status, 
    notes,
    started_at, 
    finished_at, 
    created_at, 
    updated_at
FROM sessions
WHERE user_id = $1
  AND status = 'completed'
  AND DATE(started_at) BETWEEN $2 AND $3
ORDER BY started_at DESC
`

type GetCompletedSessionsByDateRangeParams struct {
	UserID      uuid.UUID `json:"user_id"`
	StartedAt   time.Time `json:"started_at"`
	StartedAt_2 time.Time `json:"started_at_2"`
}

func (q *Queries) GetCompletedSessionsByDateRange(ctx context.Context, arg GetCompletedSessionsByDateRangeParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getCompletedSessionsByDateRange, arg.UserID, arg.StartedAt, arg.StartedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WorkoutID,
			&i.Status,
			&i.Notes,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :execrows
UPDATE sessions
SET status = $2, finished_at = $3, notes = $4, updated_at = $5
WHERE id = $1 AND status = 'active'
`

type UpdateSessionStatusParams struct {
	ID         uuid.UUID    `json:"id"`
	Status     string       `json:"status"`
	FinishedAt sql.NullTime `json:"finished_at"`
	Notes      string       `json:"notes"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionStatus,
		arg.ID,
		arg.Status,
		arg.FinishedAt,
		arg.Notes,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// GetStatsByUserAndPeriod
const getStatsByUserAndPeriod = `-- name: GetStatsByUserAndPeriod :one
SELECT
    COUNT(*)::bigint AS total_workouts,
    COALESCE(SUM(EXTRACT(EPOCH FROM (finished_at - started_at)) / 60), 0)::bigint AS total_time_minutes
FROM sessions
WHERE user_id = $1
  AND status = 'completed'
  AND started_at >= $2
  AND started_at <= $3
`

type GetStatsByUserAndPeriodParams struct {
UserID      uuid.UUID `json:"user_id"`
StartedAt   time.Time `json:"started_at"`
StartedAt_2 time.Time `json:"started_at_2"`
}

type GetStatsByUserAndPeriodRow struct {
TotalWorkouts    int64 `json:"total_workouts"`
TotalTimeMinutes int64 `json:"total_time_minutes"`
}

func (q *Queries) GetStatsByUserAndPeriod(ctx context.Context, arg GetStatsByUserAndPeriodParams) (GetStatsByUserAndPeriodRow, error) {
row := q.db.QueryRowContext(ctx, getStatsByUserAndPeriod, arg.UserID, arg.StartedAt, arg.StartedAt_2)
var i GetStatsByUserAndPeriodRow
err := row.Scan(&i.TotalWorkouts, &i.TotalTimeMinutes)
return i, err
}

// GetFrequencyByUserAndPeriod
const getFrequencyByUserAndPeriod = `-- name: GetFrequencyByUserAndPeriod :many
SELECT
    DATE(started_at) AS date,
    COUNT(*)::bigint AS count
FROM sessions
WHERE user_id = $1
  AND status = 'completed'
  AND started_at >= $2
  AND started_at <= $3
GROUP BY DATE(started_at)
ORDER BY date
`

type GetFrequencyByUserAndPeriodParams struct {
UserID      uuid.UUID `json:"user_id"`
StartedAt   time.Time `json:"started_at"`
StartedAt_2 time.Time `json:"started_at_2"`
}

type GetFrequencyByUserAndPeriodRow struct {
Date  time.Time `json:"date"`
Count int64     `json:"count"`
}

func (q *Queries) GetFrequencyByUserAndPeriod(ctx context.Context, arg GetFrequencyByUserAndPeriodParams) ([]GetFrequencyByUserAndPeriodRow, error) {
rows, err := q.db.QueryContext(ctx, getFrequencyByUserAndPeriod, arg.UserID, arg.StartedAt, arg.StartedAt_2)
if err != nil {
return nil, err
}
defer rows.Close()
var items []GetFrequencyByUserAndPeriodRow
for rows.Next() {
var i GetFrequencyByUserAndPeriodRow
if err := rows.Scan(&i.Date, &i.Count); err != nil {
return nil, err
}
items = append(items, i)
}
if err := rows.Close(); err != nil {
return nil, err
}
if err := rows.Err(); err != nil {
return nil, err
}
return items, nil
}

// GetSessionsForStreak
const getSessionsForStreak = `-- name: GetSessionsForStreak :many
SELECT
    DATE(started_at)::text AS date
FROM sessions
WHERE user_id = $1
  AND status = 'completed'
  AND started_at >= NOW() - INTERVAL '365 days'
GROUP BY DATE(started_at)
ORDER BY date DESC
`

func (q *Queries) GetSessionsForStreak(ctx context.Context, userID uuid.UUID) ([]string, error) {
rows, err := q.db.QueryContext(ctx, getSessionsForStreak, userID)
if err != nil {
return nil, err
}
defer rows.Close()
var items []string
for rows.Next() {
var date string
if err := rows.Scan(&date); err != nil {
return nil, err
}
items = append(items, date)
}
if err := rows.Close(); err != nil {
return nil, err
}
if err := rows.Err(); err != nil {
return nil, err
}
return items, nil
}
