// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: set_records.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSetRecord = `-- name: CreateSetRecord :exec
INSERT INTO set_records (id, session_id, workout_exercise_id, set_number, weight, reps, status, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSetRecordParams struct {
	ID                uuid.UUID     `json:"id"`
	SessionID         uuid.UUID     `json:"session_id"`
	WorkoutExerciseID uuid.NullUUID `json:"workout_exercise_id"`
	SetNumber         int32         `json:"set_number"`
	Weight            int32         `json:"weight"`
	Reps              int32         `json:"reps"`
	Status            string        `json:"status"`
	RecordedAt        time.Time     `json:"recorded_at"`
}

func (q *Queries) CreateSetRecord(ctx context.Context, arg CreateSetRecordParams) error {
	_, err := q.db.ExecContext(ctx, createSetRecord,
		arg.ID,
		arg.SessionID,
		arg.WorkoutExerciseID,
		arg.SetNumber,
		arg.Weight,
		arg.Reps,
		arg.Status,
		arg.RecordedAt,
	)
	return err
}

const findSetRecordBySessionExerciseSet = `-- name: FindSetRecordBySessionExerciseSet :one
SELECT id, session_id, workout_exercise_id, set_number, weight, reps, status, recorded_at
FROM set_records
WHERE session_id = $1 AND workout_exercise_id = $2 AND set_number = $3
`

type FindSetRecordBySessionExerciseSetParams struct {
	SessionID         uuid.UUID     `json:"session_id"`
	WorkoutExerciseID uuid.NullUUID `json:"workout_exercise_id"`
	SetNumber         int32         `json:"set_number"`
}

type FindSetRecordBySessionExerciseSetRow struct {
	ID                uuid.UUID     `json:"id"`
	SessionID         uuid.UUID     `json:"session_id"`
	WorkoutExerciseID uuid.NullUUID `json:"workout_exercise_id"`
	SetNumber         int32         `json:"set_number"`
	Weight            int32         `json:"weight"`
	Reps              int32         `json:"reps"`
	Status            string        `json:"status"`
	RecordedAt        time.Time     `json:"recorded_at"`
}

func (q *Queries) FindSetRecordBySessionExerciseSet(ctx context.Context, arg FindSetRecordBySessionExerciseSetParams) (FindSetRecordBySessionExerciseSetRow, error) {
	row := q.db.QueryRowContext(ctx, findSetRecordBySessionExerciseSet, arg.SessionID, arg.WorkoutExerciseID, arg.SetNumber)
	var i FindSetRecordBySessionExerciseSetRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkoutExerciseID,
		&i.SetNumber,
		&i.Weight,
		&i.Reps,
		&i.Status,
		&i.RecordedAt,
	)
	return i, err
}
