// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const countWorkoutsByUserID = `-- name: CountWorkoutsByUserID :one
SELECT COUNT(*)
FROM workouts
WHERE user_id = $1
`

func (q *Queries) CountWorkoutsByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWorkoutsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsWorkoutByIDAndUserID = `-- name: ExistsWorkoutByIDAndUserID :one
SELECT EXISTS(
    SELECT 1 FROM workouts WHERE id = $1 AND user_id = $2
) AS "exists"
`

type ExistsWorkoutByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ExistsWorkoutByIDAndUserID(ctx context.Context, arg ExistsWorkoutByIDAndUserIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsWorkoutByIDAndUserID, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getFirstWorkoutByUserID = `-- name: GetFirstWorkoutByUserID :one
SELECT 
    id, 
    user_id, 
    name, 
    description, 
    type, 
    intensity, 
    duration, 
    image_url, 
    created_at, 
    updated_at
FROM workouts
WHERE user_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetFirstWorkoutByUserID(ctx context.Context, userID uuid.UUID) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getFirstWorkoutByUserID, userID)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.Intensity,
		&i.Duration,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkoutsByUserID = `-- name: ListWorkoutsByUserID :many
SELECT id, user_id, name, description, type, intensity, duration, image_url, created_at, updated_at
FROM workouts
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWorkoutsByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListWorkoutsByUserID(ctx context.Context, arg ListWorkoutsByUserIDParams) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, listWorkoutsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.Intensity,
			&i.Duration,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
