// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: workouts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const existsWorkoutByIDAndUserID = `-- name: ExistsWorkoutByIDAndUserID :one
SELECT EXISTS(
    SELECT 1 FROM workouts WHERE id = $1 AND user_id = $2
) AS "exists"
`

type ExistsWorkoutByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ExistsWorkoutByIDAndUserID(ctx context.Context, arg ExistsWorkoutByIDAndUserIDParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsWorkoutByIDAndUserID, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
